name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: HOSTINGER_HOST

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: "sparkovationhub-todo"
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            # Set up NVM for Node.js installation
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install Node.js using NVM if not present
            if ! command -v node &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
              source ~/.nvm/nvm.sh
              nvm install 22
              nvm use 22
            fi

            # Install PM2 locally if not present
            if ! command -v pm2 &> /dev/null; then
              npm install pm2 -g
            fi

            # Deploy application
            cd /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git config --global --add safe.directory /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git fetch --all
            git reset --hard origin/main
            npm ci --production
            export PATH="$HOME/.npm-global/bin:$PATH"
            pm2 restart index.js || pm2 start index.js
