name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add package-lock.json
            git commit -m "Add package-lock.json"
            git push
          fi

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: "sparkovationhub-todo"
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git config --global --add safe.directory /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git fetch --all
            git reset --hard origin/main
            npm ci --production
            pm2 restart index.js || pm2 start index.js
