name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: HOSTINGER_HOST # Add environment specification

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }} # Using environment secret
          username: "sparkovationhub-todo"
          password: ${{ secrets.SSH_PASSWORD }} # Using environment secret
          port: 22 # Added explicit port
          debug: true # Added debug mode to help troubleshoot
          script: |
            cd /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git config --global --add safe.directory /home/sparkovationhub-todo/htdocs/todo.sparkovationhub.com
            git fetch --all
            git reset --hard origin/main
            npm ci --production
            pm2 restart index.js || pm2 start index.js
